export default function AboutSection() {
  return (
    <section id="about" className="py-20 px-6 bg-gray-50">
      <div className="max-w-4xl mx-auto text-center">
        <p className="text-sm font-medium text-gray-500 uppercase tracking-wider mb-4">
          About Us
        </p>
        <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
          Built for universities in Tarapacá
        </h2>
        <p className="text-lg text-gray-500 leading-relaxed mb-6">
          GitTableHub was founded in May 2026 to solve one of the biggest challenges in higher
          education: creating conflict-free schedules efficiently.
        </p>
        <p className="text-lg text-gray-500 leading-relaxed mb-6">
          The platform is designed to optimize resource allocation across careers, professors,
          and classrooms. Schedules are generated by our algorithm in 10 seconds.
        </p>
        <p className="text-sm text-gray-400 italic">
          
        </p>
      </div>
    </section>
  )
}
