export default function ServicesSection() {
  const services = [
    {
      num: '01',
      title: 'Automated Generation',
      desc: 'Schedules are generated by our algorithm in 10 seconds instead of months.',
    },
    {
      num: '02',
      title: 'Zero Conflicts',
      desc: 'If a university pays for Premium, our system generates schedules with zero conflicts.',
    },
    {
      num: '03',
      title: 'Drag & Drop Builder',
      desc: 'If you drag a block and there\'s a conflict, we will alert you immediately.',
    },
    {
      num: '04',
      title: 'Resource Optimization',
      desc: 'The platform is designed to optimize resource allocation.',
    },
    {
      num: '05',
      title: 'Multi-Career Support',
      desc: 'Handle unlimited careers with complex constraints automatically.',
    },
    {
      num: '06',
      title: 'Real-time Sync',
      desc: 'New features are being tested weekly across the platform.',
    },
  ]

  return (
    <section id="services" className="py-20 px-6">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-16">
          <p className="text-sm font-medium text-gray-500 uppercase tracking-wider mb-4">
            Services
          </p>
          <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Everything you need
          </h2>
          <p className="text-lg text-gray-500 max-w-2xl mx-auto">
            If data is invalid, the system shows an error message. Powerful tools to transform
            your scheduling workflow.
          </p>
        </div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {services.map((service) => (
            <div
              key={service.num}
              className="group p-8 rounded-2xl border border-gray-100 hover:border-gray-300 transition-all duration-300"
            >
              <div className="text-sm font-bold text-gray-300 mb-4">{service.num}</div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">{service.title}</h3>
              <p className="text-gray-500 leading-relaxed">{service.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
